- **Why**: Import essential libraries for data manipulation and operation.
- **Logic**: `numpy` for numerical linear algebra operations, `pandas` for handling DataFrame logic and data analysis, and `os` for interacting with the file system.
- **Achieve**: Set up the Python environment with required tools to load, process, and analyze the dataset.

In [4]:
import numpy as np 
import pandas as pd 
import os

- **Why**: Load the datasets into pandas DataFrames.
- **Logic**: Fetch data from the CSV files `tmdb_5000_movies.csv` and `tmdb_5000_credits.csv` stored locally.
- **Achieve**: Make movie and cast/crew details available in memory for manipulation, cleaning, and model development.

In [5]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

- **Why**: Preview the `movies` dataset.
- **Logic**: Display the first two rows of `movies` DataFrame using `.head(2)`.
- **Achieve**: Perform a preliminary data check to understand what features and properties are available for processing.

In [7]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

- **Why**: Check the mathematical dimensions of the `movies` dataset.
- **Logic**: Access the `.shape` attribute, which returns the number of rows and columns.
- **Achieve**: Grasp the statistical size of our movies dataset (number of entries and features).

In [8]:
movies.shape

(4803, 20)

- **Why**: Preview the `credits` dataset.
- **Logic**: Display the first few rows of the `credits` DataFrame utilizing `.head()`.
- **Achieve**: Verify the structure of the specific cast and crew information before merging operations.

In [9]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

- **Why**: Combine the two major datasets into one entity.
- **Logic**: Merge the datasets by relying on a common feature string present in both tables, the movie `title`.
- **Achieve**: Build a single comprehensive unified DataFrame containing all necessary features, ensuring that the appropriate cast and crew bind correctly with respective movie facts.

In [10]:
movies = movies.merge(credits,on='title')

- **Why**: Preview the newly merged dataset.
- **Logic**: Display the first 5 rows and log comments highlighting columns of significant contextual interest.
- **Achieve**: Evaluate the exact result of the merge operation and map out our feature selection blueprint.

In [15]:
movies.head()
# budget
# homepage
# id
# original_language
# original_title
# popularity
# production_comapny
# production_countries
# release-date(not sure)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

- **Why**: Select and keep only essential features within the merged dataset.
- **Logic**: Slice the dataset, keeping solely standard features crucial for building content-based matching algorithms: `movie_id`, `title`, `overview`, `genres`, `keywords`, `cast`, and `crew`.
- **Achieve**: Reduce system memory load and strip the data architecture of irrelevant metrics (like homepage or continuous numeric integers) preventing modeling noise.

In [16]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

- **Why**: Check the refined status of the dataset.
- **Logic**: Run `.head()` on our modified `movies` variable.
- **Achieve**: Verify that only the chosen analytical features survived the filtering stage.

In [17]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

- **Why**: Import the Abstract Syntax Tree module (`ast`).
- **Logic**: To access `ast.literal_eval`, a secure built-in tool that reliably interprets Python literals directly from strings.
- **Achieve**: Secure parsing of dictionary objects and array mappings nested inside Pandas CSV text string fragments.

In [18]:
import ast

- **Why**: Create a customized helper method to parse inner dictionary values.
- **Logic**: Pass string inputs to `literal_eval` breaking them to list entities. Traverse dictionary elements inside the list and fetch the string value assigned strictly to the `'name'` key.
- **Achieve**: Prepare functionality capable of migrating chaotic JSON-formatted text mappings natively inside Pandas columns directly to simplistic string arrays.

In [19]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

- **Why**: Eliminate null rows.
- **Logic**: Apply `.dropna(inplace=True)` on the primary dataframe.
- **Achieve**: Prevent structural breaking and calculation exceptions during text formatting sequences by permanently ensuring that datasets missing overviews or valid titles are abandoned.

In [20]:
movies.dropna(inplace=True)

- **Why**: Clean out the verbose `genres` data structure.
- **Logic**: Invoke `.apply(convert)` specifically on the `genres` textual fragments executing parsing conversion on each one separately.
- **Achieve**: Morph uninterpretable JSON string segments defining movie genres exclusively to normalized standard list formations (e.g. `['Action', 'Adventure', 'Fantasy']`).

In [21]:
movies['genres'] = movies['genres'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

- **Why**: Clean the verbose `keywords` formatting column.
- **Logic**: Push the same `.apply(convert)` parsing routine into the `keywords` text field.
- **Achieve**: Receive discrete basic term lists describing a movie's plot characteristics directly decoupled from ID integers.

In [22]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

- **Why**: Validate and test the bespoke list dictionary extraction.
- **Logic**: Execute a manual dry run passing a complex dummy string configuration holding ID values into our newly authored parameter logic wrapper.
- **Achieve**: Visualize and explicitly prove the accuracy guaranteeing that fields matching the dictionary string `name` parameter evaluate correctly.

In [25]:
print(convert('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'))

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

- **Why**: Define a stringent string parsing mechanism intended exclusively for highly limited extracts.
- **Logic**: Apply an internal counter stopping append evaluations entirely once exactly 3 matching generic target components process.
- **Achieve**: Deploy functionality ideal for extracting strictly primary major properties, minimizing noisy insignificant properties appending continuously.

In [26]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

- **Why**: Translate extensive cast data structures utilizing the first method (all casting). Wait, the previous cell was `convert3` but this runs `convert`. We are parsing string dictionaries into standard array lists.
- **Logic**: Replace raw dictionary fragments embedded across `cast` entities implementing the primary `.apply(convert)` list conversion format. 
- **Achieve**: Standardize array listings providing a fully translated cast representation for future filtering stages.

In [27]:
movies['cast'] = movies['cast'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

- **Why**: Restrict movie casts explicitly to headlining top 3 dominant talent members.
- **Logic**: Employ an anonymous inline `.lambda` trimming the Python lists keeping strictly list items matching indices `[0:3]`.
- **Achieve**: Enhance recommendation algorithms emphasizing primary starring characters since extensive backend movie extras inevitably result in disjointed cross-movie associations.

In [29]:
movies['cast'] = movies['cast'].apply(lambda x:x[0:3])
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

- **Why**: Craft logic aimed at pinpointing the primary directing creative.
- **Logic**: Implement parsing iterating safely matching raw string dictionaries ensuring parsing captures dictionary arrays with the exact explicit conditional argument: `job == 'Director'`.
- **Achieve**: Filter production staff text blocks strictly locking out executive and camera staff details prioritizing the exclusive stylistic trait unique to feature Directors.

In [30]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

- **Why**: Apply customized director parsing filters standardizing our string blocks.
- **Logic**: Feed the crew column strings running the dedicated custom `fetch_director()` function processing engine mapping over components.
- **Achieve**: Formally map over the movie data structure permanently replacing hundreds of extraneous text records down exclusively restricting the column output only capturing primary directing filmographers.

In [31]:
movies['crew'] = movies['crew'].apply(fetch_director)

- **Why**: Review operations by capturing global randomized sampling.
- **Logic**: Initiate a pandas `.sample(5)` retrieving multiple distinct data records pulled non-sequentially natively mapped across multiple sections.
- **Achieve**: Generate an objective testing visualization validating whether previous array conversions completed fully consistently bypassing sequential anomalies.

In [32]:
movies.sample(5)

,movie_id,title,overview,genres,keywords,cast,crew
1695,11249,Seed of Chucky,The killer doll is back! The all-new film is t...,"[Drama, Horror, Comedy]","[baby, puppet, filmdreh, murder, killer doll, ...","[Brad Dourif, Jennifer Tilly, Billy Boyd]",[Don Mancini]
2897,41508,Fateless,An Hungarian youth comes of age at Buchenwald ...,"[War, Drama]","[budapest, hungary, concentration camp, world ...","[Marcell Nagy, Béla Dóra, Bálint Péntek]",[Lajos Koltai]
1163,10184,He's Just Not That Into You,Remember that really cute guy who said he'd ca...,"[Comedy, Romance, Drama]","[relationship, ensemble cast, duringcreditssti...","[Ben Affleck, Jennifer Aniston, Drew Barrymore]",[Ken Kwapis]
3805,10981,Nothing,The film tells the story of two good friends w...,"[Comedy, Fantasy, Science Fiction]","[loser, bullying, leere, independent film, bes...","[David Hewlett, Andrew Miller, Gordon Pinsent]",[Vincenzo Natali]
1152,10398,Double Jeopardy,A woman framed for her husband's murder suspec...,"[Crime, Drama, Mystery, Thriller]","[prison, sailboat, sailing trip, new orleans, ...","[Tommy Lee Jones, Ashley Judd, Bruce Greenwood]",[Bruce Beresford]

- **Why**: Implement whitespace stripping functions across individual string list mappings.
- **Logic**: Rebuild lists iteratively utilizing the conventional python string substitution command `.replace(" ", "")` targeting blank spaces collapsing spaces universally.
- **Achieve**: Modify properties binding split words ensuring tagger model accuracy (preventing the model confusing `Johnny Depp` with `Johnny Galecki` directly tokenizing string representations uniquely into words like `JohnnyDepp`).

In [33]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

- **Why**: Uniformly propagate the space collapsing script replacing structural words uniformly across major elements.
- **Logic**: Redefine corresponding text arrays natively applying the internal list mapping algorithm removing isolated spaces formatting text.
- **Achieve**: Sanitize structural tags globally producing precise word classifications optimizing modeling algorithms accuracy strictly enforcing naming standards matching.

In [34]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

- **Why**: Finalize feature mapping and standardization visualizing the processed results.
- **Logic**: Query the `.head()` native functionality previewing top rows mapping over merged text datasets confirming string adjustments visually.
- **Achieve**: Provide visual proof displaying properly collapsed one-word structural strings representing array formatting cleanly.

In [35]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

- **Why**: Format standard unstructured movie description paragraph text blocks explicitly preparing for combined lists.
- **Logic**: Split raw paragraph text natively using strings basic Python default parameter token splitter via `x.split()`.
- **Achieve**: Shift native long prose natively down to token list arrays completely unifying overview text architecture merging cleanly aligned to arrays representing genres, casts etc.

In [36]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

- **Why**: Form a unified distinct global descriptive column string parameter representing movie properties entirely.
- **Logic**: Execute an array combination calculation linearly concatenating array list components extracting variables mapped individually representing elements unifying array results.
- **Achieve**: Deploy a singular massive `'tags'` list representing exclusively relevant characteristics, dropping reliance analyzing independent columns completely generating unified corpus features.

In [37]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

- **Why**: Drop redundant non-essential separated columns explicitly saving data memory footprints drastically mapping new streamlined dataframe.
- **Logic**: Leverage basic filtering calling `.drop()` completely omitting `overview`, `genres`, `keywords`, `cast`, and `crew` structures.
- **Achieve**: Filter completely resulting specifically rendering an exact minimal viable output dataset representing structural integers formatting text exclusively natively mapping our algorithm parameters.

In [38]:
new = movies.drop(columns=['overview','genres','keywords','cast','crew'])

- **Why**: Restore array formatted tokens cleanly returning raw strings.
- **Logic**: Deploy anonymous inline functionality forcing spacing components inserting `" ".join(x)` translating separated lists arrays into conventional single text strings formatting completely.
- **Achieve**: Create functional single string formats easily ingesting fully native processing functionality generating standard English paragraphs formatting algorithms native handling schemas.

In [39]:
new['tags'] = new['tags'].apply(lambda x: " ".join(x))
new.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

- **Why**: Setup textual count vector mapping tools initializing native matrix dimensions natively interpreting natural language correctly.
- **Logic**: Deploy native `CountVectorizer` mapping parameters standardizing English stop words eliminating components such as `"is"`, `"the"`, defining global limitations locking variables completely exactly processing maximum 5,000 top occurrence fields.
- **Achieve**: Produce matrix configurations uniquely primed mathematically tokenizing strings efficiently formatting algorithms recognizing text structure strictly omitting useless terminology.

In [40]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

- **Why**: Execute vector training processing string variables computing matching counts directly translating string formats completely mapping output variables mathematically.
- **Logic**: Map `new['tags']` natively targeting text arrays generating variables pushing values exclusively out generating `.toarray()`.
- **Achieve**: Produce complex 5,000 dimensional representation variables assigning individual integer matrix counts mapping completely each textual string parameter mathematically representing movie similarities explicitly.

In [41]:
vector = cv.fit_transform(new['tags']).toarray()

- **Why**: Preview dimensional matrix mapping values mapping output components correctly formatting parameters properly.
- **Logic**: Query native matrix variable running standard statistical `.shape` structural validation calculations mapping results explicitly.
- **Achieve**: Verify processing output mapping successfully mapped dimensions exactly generating exactly 4,806 arrays mapping exactly 5,000 frequency parameters tracking matrix calculations mathematically.

In [42]:
vector.shape

(4806, 5000)

- **Why**: Load dimensional geometry mapping tools interpreting multi-dimension vectors efficiently matching values.
- **Logic**: Execute importing mathematical modules mapping `cosine_similarity` calculating distance calculations based exclusively mapping geometric degrees formatting calculations efficiently.
- **Achieve**: Allow calculation algorithms matching variable formatting parameters strictly providing functionality mapping similarity variables mathematically scoring matrix matching degrees calculations explicitly.

In [43]:
from sklearn.metrics.pairwise import cosine_similarity

- **Why**: Generate similarity measurements exactly calculating distance matrix score results across thousands representing arrays mathematically.
- **Logic**: Inject text processing array vectors interpreting calculation results natively executing completely scoring calculation parameters explicitly saving matrix calculations inside `similarity`.
- **Achieve**: Build massive mapping matrices calculating distance parameters scoring exactly values 0 to 1 mapping matching movie array formats mathematical relationships indexing completely mappings efficiently.

In [44]:
similarity = cosine_similarity(vector)

- **Why**: Display computed array values validating distance formulas interpreting mathematical configurations natively executing scripts formatting parameters.
- **Logic**: Query matrix parameters displaying raw dimensional arrays mapping explicitly outputs structurally mapping values formats.
- **Achieve**: Validate multi-dimensional mapping scores calculating output matrix numbers mathematically generating outputs successfully indexing values outputs.

In [45]:
similarity

array([[1.        , 0.08964215, 0.06071767, ..., 0.02519763, 0.0277885 ,
        0.        ],
       [0.08964215, 1.        , 0.06350006, ..., 0.02635231, 0.        ,
        0.        ],
       [0.06071767, 0.06350006, 1.        , ..., 0.02677398, 0.        ,
        0.        ],
       ...,
       [0.02519763, 0.02635231, 0.02677398, ..., 1.        , 0.07352146,
        0.04774099],
       [0.0277885 , 0.        , 0.        , ..., 0.07352146, 1.        ,
        0.05264981],
       [0.        , 0.        , 0.        , ..., 0.04774099, 0.05264981,
        1.        ]])

- **Why**: Identify logical index identifiers specifically locating string arguments formatting mapping formats exactly representing variables cleanly.
- **Logic**: Deploy dataframe query calculations finding strings mapping parameter arguments formatting strings matching explicitly values extracting the zero-th parameter index variables explicitly mapping format structure parameters.
- **Achieve**: Build functionality correctly reversing string titles formatting inputs translating human parameters calculating native indexing arrays mathematically parsing explicit locations completely.

In [46]:
new[new['title'] == 'The Lego Movie'].index[0]

np.int64(744)

- **Why**: Author mapping functions querying variables displaying calculating optimal distance values representing results completely formatting similarity logic exactly.
- **Logic**: Setup algorithms identifying native locations extracting matching scores natively mapping combinations tracking reverse sorted output lists limiting results top `[1:6]` generating matching dataframe `.iloc` title variables mapping explicitly arrays formatted results.
- **Achieve**: Deploy recommendation processing generating outputs taking title strings processing math comparisons generating outputs precisely showing top optimal formatted matches completely formatting array loops efficiently.

In [47]:
def recommend(movie):
    index = new[new['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new.iloc[i[0]].title)

- **Why**: Verify native calculating parameters evaluating distance calculation accuracy mapping string strings checking values outputs.
- **Logic**: Submit textual inputs mapping "Gandhi" directly invoking customized ranking algorithms evaluating result matrices explicitly.
- **Achieve**: Prove matching system functionality mathematically evaluating top calculated similarities specifically showing mapping biographical similarities matching explicitly matching historical outputs natively formatting logic.

In [48]:
recommend('Gandhi')

Gandhi, My Father
The Wind That Shakes the Barley
A Passage to India
Guiana 1838
Ramanujan

- **Why**: Load systemic file creation mechanisms efficiently generating flat file mapping states explicitly backing outputs mapping structures completely mapping formats cleanly.
- **Logic**: Import `pickle` deploying basic Python state formatting preserving raw binary logic arrays writing state objects generating data stores natively.
- **Achieve**: Enable disk I/O functionality bypassing dataset compilation calculating exactly rendering precomputed formats formatting data explicitly preserving algorithm states outputs.

In [49]:
import pickle

- **Why**: Save memory arrays locally natively rendering file outputs locking values completely explicitly sharing systems directly mapping results efficiently avoiding constant execution values perfectly mapping files seamlessly correctly outputs values.
- **Logic**: Write Dataframes natively parsing output `movie_list.pkl` extracting datasets additionally plotting similarity calculations generating bytes formats `.dump` methods executing directly outputs streams.
- **Achieve**: Create independent offline mapping systems formatting exact mathematical computations explicitly deploying pre-computed engines efficiently saving resources mapping API states perfectly rendering applications seamlessly.

In [50]:
pickle.dump(new,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))